/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2phc29ubGV3aXMvUmVzb3VyY2VzL1dlYi1kZXYvU2NhZmZvbGRzL0FuZ3VsYXIvbG9jYWwtYW5ndWxhci1zY2FmZm9sZGluZy1hcHAvamwtYXBwL3NyYy9jb21wb25lbnRzL2FwcC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvamFzb25sZXdpcy9SZXNvdXJjZXMvV2ViLWRldi9TY2FmZm9sZHMvQW5ndWxhci9sb2NhbC1hbmd1bGFyLXNjYWZmb2xkaW5nLWFwcC9qbC1hcHAvc3JjL2NvbXBvbmVudHMvYXBwLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
